### ISSUE TITLE
Protected flag not being forwarded

### ISSUE THREAD

**Issue by hyperion032020** [Excinerus/AI-Overhaul-Patcher#9] opened 2021-06-01 03:07 UTC
The Protected flag added by AI Overhaul is not being forwarded. Not sure if related to recent update to Synthesis/Mutagen.

**Comment by Excinerus** [comment] 2021-06-13 23:52
fixed with last update

**Comment by hyperion032020** [comment] 2021-06-14 14:07
Looks like it is now forwarding that protected flag, but not always. Seems that if Bijin All in One 2020 is loaded after AI Overhaul (as it should be), it's not forwarding the protected flag. This may be occurring with other mods that get loaded after AIO, but I haven't gone through every single entry in the Synthesis patch yet.

**Comment by Excinerus** [comment] 2021-06-14 18:28
the patcher only overwrites the protection flag if the target has a lower one than AIO origin, a mod sets an npc as essential it'll remain essential.

**Comment by hyperion032020** [comment] 2021-06-15 00:54
I think I understood you correctly. So you're saying AIO sets the flag as Protected. Another mod comes and changes it to Essential. The patcher leaves this as Essential. Correct? 
This is not what is happening for me when running the patcher. AIO is setting the flag as Protected. Another mod (Bijin All in One 2020) is loading after and reverting the flag to nothing. The patcher is not restoring the Protected flag added by AIO. As can be seen here: https://imgur.com/mNARlC4

**Comment by Excinerus** [comment] 2021-06-15 05:01
I recently made the patcher skip NPCs where an Identical to last override record would result (and thus would be treated as a IDM),  could it be that you've already have that NPC patched on a different plugin. (you'll probably have to load everything on xEdit and check that specific NPC)

**Comment by Excinerus** [comment] 2021-06-15 05:42
alright Added a setting that allows users to skip Identical to last override records but it's now disabled by default

also a setting that changes the behavior when forwarding protection flags

**Comment by hyperion032020** [comment] 2021-06-15 14:09
> I recently made the patcher skip NPCs where an Identical to last override record would result (and thus would be treated as a IDM), could it be that you've already have that NPC patched on a different plugin. (you'll probably have to load everything on xEdit and check that specific NPC)

That screenshot is with my entire load order loaded in xEdit. There's nothing else modifying that character than what you see there.

I re-ran the patcher with your latest update. I tried it with and without the new option to Ignore Identical To Last Override and I'm still getting the same results as seen in that original screenshot.

**Comment by Excinerus** [comment] 2021-06-15 15:32
what other patchers are you running alongside this ? I'm having trouble reproducing this.
you can ping me on the mutagen discord, just @Excinerus

**Comment by vonLeebpl** [comment] 2021-12-31 17:37
Literally, this code doesn't work 
`patchNpc.Configuration.Flags.SetFlag(NpcConfiguration.Flag.Protected, true);`
Although my writeln to see if we are in if statement shows it's trying to forward it.
I have just this patch in synthesis order.
Can be mutagen bug?

**Comment by Excinerus** [comment] 2022-01-04 12:22
it's odd, that might be the case, I was unable to reproduce that behavior, 
![image](https://user-images.githubusercontent.com/6299495/148058130-e8446653-e708-43fc-b55c-62ab25d81627.png)
Edit: I just looked at your conversation with noggog, didn't have to reassign the flags on the version I wrote this patch on, I'll update that, thanks !

**Comment by Excinerus** [comment] 2022-04-28 21:48
Fixed in  [2a4fc97](https://github.com/Excinerus/AI-Overhaul-Patcher/commit/2a4fc974842e0d175536a65b3d29f944f4649a5c)

**Closed as completed by Excinerus** 2022-04-28 21:48 UTC
